### ISSUE TITLE
Trestle Catalog Generate does not write parameters For NIST 800-53r4 sample json

### ISSUE THREAD

**Issue by deenine** [IBM/compliance-trestle#1042]
## Describe the bug

Per https://github.com/IBM/compliance-trestle/pull/999/files `trestle author catalog-generate` should write the parameters for the control into its markdown file, this works with trestle formatted oscal json:
```
"controls": [
          {
            "id": "ac-1",
            "title": "Access Control Policy and Procedures",
            "params": [
              {
                "id": "ac-1_prm_1",
                "values": [
                  "organization-defined personnel or roles"
                ]
              },
              {
                "id": "ac-1_prm_2",
                "values": [
                  "organization-defined frequency"
                ]
              },
```

but does not work with [the sample file provided by NIST](https://github.com/usnistgov/oscal-content/blob/main/nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_catalog.json):
```
"controls": [
          {
            "id": "ac-1",
            "class": "SP800-53",
            "title": "Access Control Policy and Procedures",
            "params": [
              {
                "id": "ac-1_prm_1",
                "label": "organization-defined personnel or roles"
              },
              {
                "id": "ac-1_prm_2",
                "label": "organization-defined frequency"
              },
              {
                "id": "ac-1_prm_3",
                "label": "organization-defined frequency"
              }
```

## Expected behavior

Parameters in markdown:
```
---
x-trestle-set-params:
  ac-1_prm_1: organization-defined personnel or roles
  ac-1_prm_2: organization-defined frequency
  ac-1_prm_3: organization-defined frequency
---

# ac-1 - \[Access Control\] Access Control Policy and Procedures
```

**Comment by fsuits** [comment]
@deenine I think the different behaviors are due to having *values* assigned in one case, but only *labels* present with no values in the second case.

I have used different interpretations of how to handle this, but currently the parameters are only output in the header if they have *values* assigned.  There is no simple way to tell a descriptive *label* from an intended *value* during catalog assemble.  So the header is only created for parameters with *values* and during assembly the prose is regarded as *values* that should be assigned to the params in the new catalog.  I think if we want the descriptive label to be output, then the header would need to have separate label and value entries for each parameter.  In that case every header would have all parameters, and separate key/values for label and value.  Is that or something else the preferred approach?  See example below.  One of the params has both a label and a value and the value would be assigned in the assembled catalog.

For Selections I could provide additional key/value pairs.  Is that desired?  The header may get large.

If we do it this way, I would regard any changes to the label as intentional and make the corresponding change in the catalog's control label for the param.  If no value is provided I would have no value for the parameter in the catalog's control - just the label.

```
---
x-trestle-set-params:
  ac-1_prm_1: 
    label: organization-defined personnel or roles
    value:
  ac-1_prm_2: 
    label: organization-defined frequency
    value: daily
  ac-1_prm_3:
    label: organization-defined frequency
    value:
---
```
