### ISSUE TITLE
Features needed for ssp generate and assemble

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#1260]
## Issue description / feature objectives

1. ssp-assemble should allow option to list original comp_def's so that uuid's are preserved
2. make all header lists be lists even if one item
3. ssp-generate should have comp-defs optional so that system response can be provided for all controls - without comp defs
4. Empty lists in header []
5. Put brackets around params in prose
6. convert all Add... prompts to comments
7. Make description either empty or pulled from markdown
8. Make sure ImplementationStatus behaves propertly - from common.py
9. @vikas-agarwal76 Decide if all parts needed so system responses are possible
10. Fix misplaced prompt under components in md

**Comment by vikas-agarwal76** [comment]
Move the association of rule_name to param and it should be called rule-id  Currently, the Markdown has -
```
x-trestle-rules-params:
  HPCS:
    - name: hpcs_crypto_units
      description: Hyper Protect Crypto
      options: '3'
x-trestle-comp-def-rules-param-vals:
  HPCS:
    - rule_name: hyperprotect_crypto_units_min_count
      name: hpcs_crypto_units
      values:
        - '2'
```

This should be changed to -
```
x-trestle-rules-params:
  HPCS:
    - name: hpcs_crypto_units
      description: Hyper Protect Crypto
      rule-id: hyperprotect_crypto_units_min_count
      options: '3'
x-trestle-comp-def-rules-param-vals:
  HPCS:
    - name: hpcs_crypto_units
      values:
        - '2'
```

**Comment by vikas-agarwal76** [comment]
Assemble issues in JSON -
1. import-profile->href has "REPLACE_ME". Since we already provided profile during generate, it should use that (maybe we need to store profile name also in addition to profile title in markdown to use it) or take the profile name / URL as part of assemble command line arguments. Second option may be simpler as we anyways plan to take component defs during assemble.
2. system-implementation->components. For "This system", the type should be set to "this-system". There is a specific type for the overall system defined in OSCAL
3. For other components use the"type" and "description" from the component-defs if specified as a command line argument.
4. All the rules (and its metadata like desc, params, etc.) should be populated in the system-implementation->components. Currently it is not there. One easy way may be get the props for a component from CD JSON and just put it as it is here.
5. Rule mapping for control-id or statement id in by-components is not there. This should be included.

**Comment by fsuits** [comment]
I think all these changes point to just using the actual compdefs during assemble.  The whole assembly process only needs limited info from the yaml header since only limited user-edits are allowed there.  For now I can address the item above this one, and item 2 in this list.  Separately I will add compdefs to the command line option for assemble and pull everything from the actual components.

**Comment by vikas-agarwal76** [comment]
@fsuits 
During ssp generate - 
1. instead of "rule_name" it should be called "rule-id". Please see the example in message above
```
x-trestle-rules-params:
  HPCS:
    - name: hpcs_crypto_units
      description: Hyper Protect Crypto
      options: '3'
      rule_name: hyperprotect_crypto_units_min_count
```
2. Comment is missing for how to specify control parameter values. "ssp-values"
3. -cd argument should be made optional in which case all control md files should be genearted with default "This System" component. Currently this argument is required.

During ssp assemble -
1. import-profile still has RPLACE_ME instead of the href from Markdown
2. set-parameter for component rule values are not being generated in assembled JSON though it is being generated for control parameters set using ssp-values.
