### ISSUE TITLE
Insert yaml objects as properties with respect to control responses.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#654]
## Issue description / feature objectives
The FedRAMP OSCAL template (as an example) has a small number of properties that are required to respond to each *control*.

One approach to populate these would be to pull from the yaml headers that are optional to control responses.

E.g. in the fedramp case:
```yaml
control-origination:
  - Service provider Corporate
  - Service provider System Specific
  - Service Provider Hybrid (Corporate and System Specific)
  - Configured by Customer (Customer System Specific) 
  - Provided by Customer (Customer System Specific)
  - Shared (Service Provider and Customer Responsibility)
  - Inherited from pre-existing FedRAMP Authorization [Enter text here], Date of Authorization 
implementation-status:
  - Implemented
  - Partially implemented
  - Planned
  - Alternative implementation
  - Not Applicable
responsible_role:
planned-completion-date:
```
Where arrays would get flattened to comma separated text.

The challenge here would be this may restrict users too far in that it would limit how the yaml header could be used. An improved approach would be
```yaml
stuff: here 
bar: information is not pulled into properties
control-properties: # A special property
    property-name: property-value
    # note within control properties no nesting is allowed..
```

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version / branch:
- Platform:
- Subsystem:
