### ISSUE TITLE
Inject fedramp specific control metadata into ssp-assemble workflow.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#891]
## Issue description / feature objectives
Fedramp SSP's contain 3 pieces of metadata as outlined in pages 36-38 of the 'Guide to OSCAL based FedRAMP System Security Plan (SSP)'
- Responsible Role(s)
- Implementation status
- Control origination 

In order to process properties we need to know which fields should be processed into properties. For this proposing `x-trestle-props` to flag that these into props.

The objective would be `x-trestle-props` would be used for any arbitrary `name` `value` pair for props.

For _FedRAMP_ properties the `control-origination` `implementation-status`, `responsible-role` would be processed specifically into the fedramp namespace.

For `control-origination` and `implementation-status` this should enforce that the items are from the expected drop down list.

For responsible roles it is expected that users will provide the descriptive 'role-id' e.g. `admin-unix` etc.

Sample yaml header.
```yaml

x-trestle-props:
  control-origination: # here the appropriate attributes are selectr from the list and put into the properties
    - Service provider Corporate
    - Service provider System Specific
    - Service Provider Hybrid (Corporate and System Specific)
    - Configured by Customer (Customer System Specific) 
    - Provided by Customer (Customer System Specific)
    - Shared (Service Provider and Customer Responsibility)
    - Inherited from pre-existing FedRAMP Authorization [Enter text here], Date of Authorization 
  implementation-status:
    - Implemented
    - Partially implemented
    - Planned
    - Alternative implementation
    - Not Applicable
  responsible_role:
  planned-completion-date:
```

## Caveats / Assumptions
- SSP Generate will rely on the yaml headers. This will only apply for SSP-Assemble. 
- Expect that future capability will go into profiles and catalogs[
- 
## Attached documents: 
[Guide_to_OSCAL-based_FedRAMP_System_Security_Plans_(SSP)-3.pdf](https://github.com/IBM/compliance-trestle/files/7594060/Guide_to_OSCAL-based_FedRAMP_System_Security_Plans_.SSP.-3.pdf)
[Guide_to_OSCAL-based_FedRAMP_Content-2.pdf](https://github.com/IBM/compliance-trestle/files/7594063/Guide_to_OSCAL-based_FedRAMP_Content-2.pdf)
